# Generated by Django 4.2.7 on 2023-11-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='email_address',
            field=models.EmailField(max_length=100),
        ),
    ]
