# Generated by Django 4.2.7 on 2023-11-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_imageupload_alter_uploaddesign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddesign',
            name='image',
            field=models.ImageField(upload_to='uploaded/'),
        ),
    ]
