# Generated by Django 4.2.7 on 2023-11-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_imageupload_alter_uploaddesign_image'),
        ('designs', '0002_profile'),
    ]

    operations = [
    ]
