# Generated by Django 4.2.7 on 2023-11-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_alter_uploaddesign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='uploaded'),
        ),
        migrations.AlterField(
            model_name='uploaddesign',
            name='image',
            field=models.ImageField(upload_to='uploaded'),
        ),
    ]
