# Generated by Django 4.2.7 on 2023-11-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_alter_imageupload_image_alter_uploaddesign_image'),
        ('designs', '0004_rename_profile_designer'),
    ]

    operations = [
    ]
