# Generated by Django 4.2.7 on 2023-11-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_merge_20231128_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='s3://design-on-demand-static/media/uploaded/'),
        ),
    ]
