# Generated by Django 4.2.7 on 2023-12-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0012_delete_designproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uploaddesignerdesign',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='uploaddesignerdesign',
            name='user',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='uploaded'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Designer',
        ),
        migrations.DeleteModel(
            name='UploadDesignerDesign',
        ),
    ]
